### ISSUE TITLE
Add `flow_builder` to the preliminary comparative analysis

### ISSUE THREAD

**Issue by iapicca** [flutter/uxr#26]
I'm not very confident in advancing this proposal as the package I'm referring to is not mine, but @felangel 's

for completeness I'd consider adding [flow_builder](https://github.com/felangel/flow_builder) to the [packages included in the analysis](https://github.com/flutter/uxr/blob/master/nav2-usability/comparative-analysis/README.md#packages-included-in-the-analysis)

**Comment by slovnicki** [comment]
flow_builder really depicts declarative routing beautifully, but is still missing `Router` integration as @felangel is surely extremely busy with other great packages. (fan here)

As I'm currently aware, there really is no way of doing the general app navigation without any imperative API. Two reasons I'm seeing are:

1. Many users, especially new, are more comfortable with `navigateTo(<something>)`-like API
2. Pushing an intent from OS is naturally imperative. We could just disguise it in declarativeness

My opinion is that we must seek a solution that provides both, something I'm trying to accomplish with [beamer](https://github.com/slovnicki/beamer). I explain the core concepts and mechanics in [this comment](https://github.com/flutter/uxr/issues/15#issuecomment-803635221) where I also mention the idea of "imperative through + declarative within". You will notice how, among many others, I have an [ `update` function](https://github.com/slovnicki/beamer#updating) that looks very much like flow_builder's because, really, there's no better way to do it.

**Comment by felangel** [comment]
Fwiw I’m working on a proposal to add routing support to flow_builder. I was just busy getting bloc v7.0.0 these last few weeks.

**Comment by jackkim9** [comment]
@iapicca, thanks for opening the issue! (and thanks @slovnicki and @felangel for adding your thoughts/comments here) This has been brought up: https://github.com/flutter/uxr/issues/7#issuecomment-801583801 It sounds like there’s community interest in including this package. 

At the moment, we are accepting PRs to continue updating the [analysis](https://github.com/flutter/uxr/blob/master/nav2-usability/comparative-analysis/README.md#packages-included-in-the-analysis). Is there anyone from the community interested in adding their assessments in the table?

**Comment by Gene-Dana** [comment]
@jackkim9 Sure thing ! Just want to make sure that I have everything correct before submitting

**Comment by jackkim9** [comment]
Thanks @Gene-Dana for the PR! I made some minor adjustments to make the table show up correctly. 

@felangel, please feel free to comment on this PR: #29

**Comment by nguyenxndaidev** [comment]
> At the moment, we are accepting PRs to continue updating the [analysis](https://github.com/flutter/uxr/blob/master/nav2-usability/comparative-analysis/README.md#packages-included-in-the-analysis). Is there anyone from the community interested in adding their assessments in the table?

I am working to add **[Navi](https://github.com/zenonine/navi/tree/master/navi)** to the game.

**Comment by felangel** [comment]
Just drafted an initial proposal to add routing support for flow_builder at https://github.com/felangel/flow_builder/issues/41.
