### ISSUE TITLE
"Skipping stacks" use cases

### ISSUE THREAD

**Issue by InMatrix** [flutter/uxr#5]
As part of the [Navigator 2.0 API Usability Research](https://github.com/flutter/uxr/wiki/Navigator-2.0-API-Usability-Research), we are looking for concrete use cases where an app's navigation stack needs to be changed arbitrarily thus making it necessary to use Flutter's Navigator 2.0 API. If your app has this use case, please describe it in this thread.

**Comment by nguyenxndaidev** [comment]
If I can control the history stack, normally related to Back action, I will
* configure to remove all routes I don't want them appear in the history globally. This way is quite useful because instead of `pushReplacement()`, I just use `push()` and don't care about the history at the place I navigate. The global configuration will check if any route is allowed to be added to history.
* definitely not allow continuously duplicated items in the history. For example, I will try to make route history like this `[A, B, A, A, B, A, A, A]` becomes `[A, B, A, B, A]`.

For the hierarchy stack, normally related to Up action, I sometime want to go upper in the route hierarchy multiple levels and skip some levels in between.

**Comment by InMatrix** [comment]
@nguyenxndaidev Is there an existing package that support the use cases you mentioned? I'd love to see a few examples. Thanks!

**Comment by nguyenxndaidev** [comment]
@InMatrix No, I don't see any package doing things like this yet. I am currently developing a copy of angular and also tried this idea and it seems it works. But there's still an edge case when I try to implement both AntPath pattern and the up action.
For example, if I have routes like below:
```
Route(
  path: 'a/**'
  children: [
    path: '**/z'
  ]
)
```

Assume current route is `a/b/c/z` and we want to go up 1 level in the hierarchy, we don't know which one is the correct one: `a/b` or `a/b/c`. Currently, I am thinking a solution for this problem.

**Comment by nguyenxndaidev** [comment]
My architecture to have a full control of history stack and hierarchy stack is to create a state layer between library's navigation interface and flutter's navigator. So I can check route lifecycle and manipulate everything I need before delegate the final action to flutter navigator.

**Comment by nguyenxndaidev** [comment]
The related problem mentioned in https://github.com/flutter/flutter/issues/77360 is also quite interesting.

**Comment by InMatrix** [comment]
@nguyenxndaidev After considering your comments above and the example from flutter/flutter#77360, I start to realize the "Skipping Stacks" scenario illustrated in our storyboard doesn't describe one of the most important motivations of creating Navigator 2.0's declarative API – giving the developer full control over the Navigator's history stack. 

There are a few concrete scenarios where this capability is useful:

- Restoring the app's navigation history upon restarting the app (see https://github.com/flutter/flutter/issues/12146#issuecomment-450841672) 
- Adding multiple pages to the history stack while showing the transition to the last one to the user (see https://github.com/flutter/flutter/issues/12146#issue-258569518)
- Simplifying the history stack by removing duplicate items (flutter/flutter#77360 and your comment above https://github.com/flutter/uxr/issues/5#issuecomment-778752913)

In contrast, the current "Skipping Stacks" storyboard shows the user going to a specific page upon clicking an in-app back button:

![image](https://user-images.githubusercontent.com/348942/110424463-b5784400-8057-11eb-80d5-17034ada2eb3.png)

This seems to be achievable with the `Navigator.pushNamed` method in Navigator 1.0. Is my understanding correct?

**Comment by InMatrix** [comment]
@johnpryan I think it would have been the case as you described, if Theo clicks the _Back button in the browser_ instead of a button inside of the app at Step 3 of the storyboard.  The transition between Step 3 and Step 4 seems to be achievable by pushing a named route for the category landing page, no? The history stack at the end of this scenario would look like this: [Homepage, Search Results, Product Detail, Category Landing Page].

**Comment by johnpryan** [comment]
The browser back button takes the user to the previous route path in the URL, whatever that is. At step 3, if the user presses the browser back button they will be taken to the Search Results screen. 

The transition between step 3 and step 4 *could* push a new page onto the stack, but that's not how I was interpreting it, and it wouldn't be an example of changing the stack of pages.

I think the page stack at step 4 is ambiguous, and we probably need to clarify what is going on from the developer's point of view. I see a couple of options, the first is that the page stack information could be added to the scenario. The other option would be an additional step (maybe another back button press) to show that the stack of pages was modified in some way,  for example the Search Results page was removed, and pressing the back button takes the user back to the Homepage.

**Comment by InMatrix** [comment]
> I think the page stacks at steps 3 and 4 are ambiguous

Yes, I agree. The ambiguity has led to misinterpretation of this scenario. For example, VRouter's implementation of this scenario didn't really modify the stack, if I read the code correctly. 

https://github.com/lulupointu/vrouter_navigator_scenarios/blob/main/lib/skipping_stacks.dart#L131

I'm a bit confused by the terminology used in this discussion so far. Is the "history stack" the same as "the page stacks"? And are there more than one stack? The [design doc](https://docs.google.com/document/d/1Q0jx0l4-xymph9O6zLaOY4d_f7YFpNWX_eGbzYxr9wY/edit#) of Navigator 2.0 talks about "the history stack of the Navigator." Assuming we're all referring to this stack, I'd like the scenario to demonstrate a need for making surgical changes to the history stack in order to satisfy a plausible goal of the end-user. I agree with @johnpryan that we can add a step to the existing "skipping stacks" scenario to demonstrate the stack changes. For example, when the user pushes the browser's back button at the end of the scenario, they go back to the homepage. However, I'm afraid the scenario would feel a bit contrived. This doesn't seem to be a common navigation behavior on e-commerce sites. 

Maybe there is a simpler and more natural scenario we can use to demonstrate the need for the capability of arbitrarily modifying the history stack of the Navigator?

**Comment by tomgilder** [comment]
@InMatrix this is slightly contrived, but how about purchasing an in-app upgrade as an example of that?

<img width="723" alt="Screenshot 2021-03-10 at 11 53 43" src="https://user-images.githubusercontent.com/756862/110610819-473a9b00-8197-11eb-81ac-cc24767aca8e.png">

**Comment by InMatrix** [comment]
Thinking on this scenario a bit more, I think I might have conflated the "Skipping Stacks" and "Editing the History Stack" scenarios. To illustrate the differences between the two scenarios, I created the following diagrams:
![Skipping Stacks vs  Manipulation of History Stack](https://user-images.githubusercontent.com/348942/110680082-09387980-818d-11eb-8f55-f290ecfa2548.png)

The "Skipping Stacks" scenario, IIUC, seems to require the presence of multiple Navigators, since by definition, one navigator manages one history stack. This scenario seems to be explicitly supported by the beamer package. Specifically, each BeamerLocation has its own stack, and beaming between different BeamerLocations takes the user to a different stack of pages. 

> You can think of it as teleporting (beaming) to another place in your app. Similar to Navigator.of(context).pushReplacementNamed('/my-route'), but Beamer is not limited to a single page, nor to a push per se. You can define an arbitrary stack of pages that gets build when you beam there. Using Beamer can feel like using many of Navigator's push/pop methods at once. (https://github.com/slovnicki/beamer#key-concepts)



The "Editing the History Stack" scenario would require direct access to the history stack beyond `push` and `pop`, which Navigator 2.0 enables with the pages API. I'm not sure which package currently does that. 

Question to folks following this discussion:
- Is my understanding about the differences between the two scenarios correct?
- Which one of these scenarios a developer of small-to-medium-sized app would expect Flutter to support?

@tomgilder Thanks for coming up with this example. IIUC, the pages for upgrading the app to premium will be removed from the history stack once the user has made the purchase. Therefore, the user would be taken back to the Homepage after the purchase. Is that correct?

**Comment by slovnicki** [comment]
@InMatrix I believe you have a typo in diagram; it should be "Clicking the browser's back button at B2 will take the user to A4 instead of B1." (a different behavior than AppBar's back button).

> The "Skipping Stacks" scenario, IIUC, seems to require the presence of multiple Navigators, since by definition, one navigator manages one history stack.

True. Unless the package is internally keeping some notion of a "stack of page stacks", each of which is built by the same Navigator.

> This scenario seems to be explicitly supported by the beamer package.

True.

About "Editing the History Stack" :
I don't consider this of much importance because

- if we are using the Pages API, this cannot happen
- if duplicates exist in a stack, they are a product of `push` actions. User can push arbitrary MaterialPages onto stack which can have exact same content, but how can we go about comparing this content that is a **user-defined** `Widget`? Only by `runtimeType`, but this does not guarantee that the content is the same.

**Comment by tomgilder** [comment]
> @tomgilder Thanks for coming up with this example. IIUC, the pages for upgrading the app to premium will be removed from the history stack once the user has made the purchase. Therefore, the user would be taken back to the Homepage after the purchase. Is that correct?

Yes, that's what I was thinking.

User presses back, goes back to the (newly upgraded) homepage. That's the best example I can think of currently.

**Comment by InMatrix** [comment]
> @InMatrix I believe you have a typo in diagram; it should be "Clicking the browser's back button at B2 will take the user to A4 instead of B1." (a different behavior than AppBar's back button).

No, it wasn't a typo. I did believe the user would go from B2 to B1 when clicking the browser's back button while at B2, since the user has switched to the B stack completely at that point. If the user still goes back to A4 from B2, how is this different from just pushing B2 to the A stack after the user has visited A4? Maybe I still misunderstand something. 

> if we are using the Pages API, this cannot happen

Could you clarify what cannot happen if we're using the Pages API?

> Keeping the history clean of duplicates in the sense of flutter/flutter#77360 is more related to keeping the "stack of stacks" clean, as each tab is separate stack there. Beamer solved this also at slovnicki/beamer#117 (link to a commit that closed it is also in issue). 

This is a very useful explanation. Thanks!

**Comment by slovnicki** [comment]
@InMatrix As is my understanding, browser keeps a history of visited URLs and browser's back/forward buttons go through these. This is not related to an in-app back button, but sometimes they may appear as if they are doing the same thing. Let me try to draw a table of actions, URLs, and app's Page stack.

### Browser

| Step | Action | URL | Pages (can vary by implementation) |
|-|-|-|-|
| 1 | initial | /  | Home |
| 2 | press an app button to go to profile | /profile | Profile |
| 3 | press an app button to go to profile details | /profile/details | Profile,Details |
| 4 | **press browser's back button** | /profile | Profile |
| 5 | manually type /shop/cart in URL bar | /shop/cart | Shop,Cart |
| 6 | **press browser's back button** | /profile | Profile |

### App

|Step | Action | URL | Pages (can vary by implementation) |
|-|-|-|-|
| 1 | initial | /  | Home |
| 2 | press an app button to go to profile | /profile | Profile |
| 3 | press an app button to go to profile details | /profile/details | Profile,Details |
| 4 | **press app's back button** | /profile | Profile |
| 5 | manually type /shop/cart  in URL bar | /shop/cart | Shop,Cart |
| 6 | **press app's back button** | /shop | Shop |

Notice how in step 4 the app's and browser's button seem to behave the same, but are not behaving the same in step 6. This is because app's back button will always do `pop` on the page stack, but browser knows nothing about that and just puts the last visited URL in the URL bar. Then the app's router receives this URL and parses it (using only the available information from URL) into appropriate Page stack.

### Why I thought it was a typo in diagram?

As 2 seemingly different stacks were drawn, I assumed that As would have the URL representation `/A1/A2/A3/A4` and Bs `/B1/B2`. So in this case, the browser's back button will take the user to last visited URL, which is `/A1/A2/A3/A4`. This is also why I remarked that it would maybe make more sense to update `/A1/A2/A3/A4` into `/A1/A4`. But still, browser's back will go to `/A1/A2/A3/A4`. There would need to be a mechanism in the app's router to determine then that `/A1/A2/A3/A4` is not OK anymore as user has upgraded, so it updates the URL to `/A1/A4`. To user, there would be no change in app, as `A4` is up front all the time.

But now it seems we're diving into the topic of `state -> `url` which is a hot topic at https://github.com/flutter/uxr/issues/15 :)

---

> Could you clarify what cannot happen if we're using the Pages API?

I should have said "if we are **only** (no `push`/`pop`) using the Pages API, this cannot happen".
Because then every navigation event builds an upfront defined, state-interactable stack of pages for `Navigator.pages`. There is no reason to **define** duplicates.

**Comment by johnpryan** [comment]
> Is the "history stack" the same as "the page stacks"?

The browser history stack is not the same as the page stack managed by the Navigator. This is an important distinction, and for the purposes of this scenario I am focusing on the Navigator stack. We designed the relationship between the browser history and Navigator page history to be similar to Gmail. For example, navigating to `/inbox`, then to an email `/inbox/abcdef` and then pressing the app back button takes you back to `/inbox`. At this point the browser history is `['/inbox', '/inbox/abcdef', '/inbox']` and the app history stack is `['inbox']`. This is currently hardcoded into the Flutter engine and isn't likely to change.

> The "Skipping Stacks" scenario, IIUC, seems to require the presence of multiple Navigators

At first glance, I don't think I understand the difference between "Skipping Stacks" and "Editing the History Stack".

**Comment by nguyenxndaidev** [comment]
Sorry for joining the party late!

Firstly, we should check this nice page https://material.io/design/navigation/understanding-navigation.html

![image](https://user-images.githubusercontent.com/24372782/110974745-2755d380-835f-11eb-90f0-62ab6aecf6ab.png)

![image](https://user-images.githubusercontent.com/24372782/110974859-4bb1b000-835f-11eb-8b19-36897fa417ed.png)

### According the material guideline, we need to manage 2 kinds of stacks
1. History stack

    In Browser, each tab has a **single history stack**. Press browser Back and Forward buttons to travel this history stack.
    In Browser, we can use [History API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/history) and [Location API](https://developer.mozilla.org/en-US/docs/Web/API/Location#methods) to control the history stack.

    In Native App, press **system Back button** to travel the history stack. This button should behave exactly like the browser Back button. Please don't mix this behavior with the **AppBar Up button** (the name is according to material guideline).
    Flutter Nav 2.0 currently doesn't have an API to fully control history stack. The only place Flutter interacts with history stack is to return `null` or `not-null` value in the [RouteInformationParser.restoreRouteInformation method](https://api.flutter.dev/flutter/widgets/RouteInformationParser/restoreRouteInformation.html).
    This approach doesn't work if I want to update the history stack (ex. remove duplicate URLs in the past).

2. Hierarchy stack

    An app (a tab in Browser) could have **multiple hierarchy stacks**.
    Flutter Nav 2.0 manages these stacks with [`Navigator.pages`](https://api.flutter.dev/flutter/widgets/Navigator/pages.html)

### Users navigate to a new page in different ways
1. In Browser, **enter an URL** manually.
2. In Browser, press **browser Back button**. Technically, this behaves the same like 1.
3. In Native App, press **system Back button**. According to material guideline, this button should behave like the **browser Back button**.
4. In both Native App and Browser, press **AppBar Up button**. According to material guideline, this button should navigate to the upper page of hierarchy stack.
5. Click somewhere in the viewport. Developers should be able to decide
    * navigate to any URL. Depends on the target URL, the hierarchy stack could be a new stack.
    * call `back()` to travel the history stack. Depends on the target URL, the hierarchy stack could be a new stack.
    * call `up()` to travel the current hierarchy stack.
6. Navigate without user interaction. For example, ask for login if session expired, showing Ads in free apps, etc.
7. Do I miss other ways?

### What developers can and cannot with current Nav 2.0?
1. Can control hierarchy stack with `Navigator.pages`
2. Cannot control history stack
3. **System Back button** and **AppBar Up button** are considered in Nav 2.0 as the same thing of a `pop()`. This is a big mistake of Nav 2.0. I think, developers should be able to configure this behavior globally.

### Skipping stacks
Do you mean: "Change from hierarchy stack A to hierarchy stack B"?

From beginning, I thought you just mean generally: "Removing items in history stack and hierarchy stacks."

I think we can have 2 separated tickets for managing each kind of stacks and link them.
The management of these 2 kinds of stacks don't need to have any relationship.
For me, every time navigating to a URL, 2 parallel actions will be triggered independently:
* Build a hierarchy stack for the given URL.
    * The result of this action doesn't need to know about history stack.
    * Do we need to identify we are still in the same hierarchy stack or in a new hierarchy stack? IMO, maybe we don't need to care that. Just always build a hierarchy stack for a given URL then update the `Navigator.pages` with the right key for each page. And it will just work.
* Manipulate the history stack.
    * The result of this action doesn't need to know about hierarchy stacks.
    * Navigate to a URL in history stack should be considered as entering a URL, nothing special here.

**Comment by InMatrix** [comment]
Thanks all for your explanations. Very helpful!

**Comment by tomgilder** [comment]
> **System Back button** and **AppBar Up button** are considered in Nav 2.0 as the same thing of a `pop()`. This is a big mistake of Nav 2.0. I think, default behavior should follow material guideline. But developers should be able to configure to change default behavior globally.

This is such an important point, and I feel it's currently being missed in the scenarios we have.

I'm currently trying to implement this on [Routemaster](https://github.com/tomgilder/routemaster), and it gets pretty complicated.

If we have stack `[A, B, C]` and a button on page C jumps to the stack `[A, Y, Z]` then pressing the Android or web browser back button should take them back to `[A, B, C]`. But the "up" button (arrow in top-left corner) should take them to `[A, Y]`.

This should ideally be automatic and not something the developer should care about.

**Comment by johnpryan** [comment]
Thanks for sharing the [Understanding Navigation](https://material.io/design/navigation/understanding-navigation.html) docs @nguyenxndaidev. That's a really helpful page.

In the [Reverse navigation](https://material.io/design/navigation/understanding-navigation.html#reverse-navigation) section of that page, there is a distinction between "Reverse chronological navigation" and "Upward navigation".

In Flutter, the browser back button behavior is **reverse chronological** since it navigates the user through the recently viewed screens, and the app back button is **upward**, since it navigates the user upwards in the app hierarchy (or "page stack" as we sometimes call it.)

**Comment by nguyenxndaidev** [comment]
> In Flutter, when you use the Router widget, the browser back button behavior is **reverse chronological** since it navigates the user through the recently viewed screens

@johnpryan could you please give a quick example how to use Router widget to navigate to recently viewed screen?

**Comment by johnpryan** [comment]
@nguyenxndaidev When you use the Router widget (RouteInformationParser and RouterDelegate) the browser back button will behave according to the reverse chronological section of that document. We have a sample [here](https://github.com/flutter/samples/blob/master/navigation_and_routing/lib/router/router.dart)

**Comment by tomgilder** [comment]
Are there any differences between how the system back button on Android and a web browser back button should behave? As far as I can think they should have the exact same behaviour. But I'm assuming other people have thought about this 😀

**Comment by johnpryan** [comment]
Right now the Android back button doesn't have the same behavior as the browser's back button.
