### ISSUE TITLE
Rename "Navigator 2" to "Router" throughout

### ISSUE THREAD

**Issue by Hixie** [flutter/uxr#79]
It would be great if we could move away from the term "Navigator 2" here. It seems to be causing some confusion (e.g. https://www.reddit.com/r/flutterhelp/comments/rmf4w4/difficulty_with_navigator_20/ links to this repo as an example of "Navigator 2" rather than as an example of "Router").

**Comment by InMatrix** [comment]
Sure, I'm updating the following places where "Navigator 2.0" is mentioned:

- [X] Wiki pages
- [ ] Markdown files
- [ ] Folder names
- [ ] PDF files

I'm inclined to not touch closed issues and PRs, since few people will look at them again.

**Comment by InMatrix** [comment]
https://github.com/flutter/uxr/pull/80 has been created to update markdown files and pdf files. I'm hesitant to change the folder name "nav2-usability" because it will break a lot of links to artifacts in it. The Readme file for that folder will have no reference to "Navigator 2.0" after the PR lands. Is that Okay?

**Comment by Hixie** [comment]
i mean all of this is best effort, i don't think we'll ever eradicate the name entirely...
